// utils/req_res.h
#pragma once

#include "utils/buffer.h"
#include "utils/constants.h"
#include "utils/container_of.h"
#include "utils/dlist.h"
#include "utils/hashtable.h"
#include "utils/timer.h"
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <string>
#include <unistd.h>
#include <vector>

struct Conn {
    int fd = -1;
    // application's intention, for the event loop
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;
    // buffered input and output
    Buffer incoming; // data to be parsed by the application
    Buffer outgoing; // responses generated by the application
    // Keeping track for timer
    uint64_t last_active_ms = 0;
    DList idle_node;
};

// the whole key-value store: a hash table of Entry, one per key
static struct {
    HashTable db;
    std::vector<Conn*> fd2conn;
    DList idle_list;
} g_data;

void do_request(std::vector<std::string>& cmd, Buffer& out);
auto read_u32(const uint8_t*& cur, const uint8_t* end, uint32_t& out) -> bool;
auto read_str(const uint8_t*& cur, const uint8_t* end, size_t n, std::string& out) -> bool;
auto parse_req(const uint8_t* data, size_t size, std::vector<std::string>& out) -> int32_t;
static void conn_destroy(Conn* conn) {
    (void)close(conn->fd);
    g_data.fd2conn[conn->fd] = nullptr;
    dlist_detach(&conn->idle_node);
    delete conn;
}
static void process_timers() {
    uint64_t now_ms = get_monotonic_msec();
    while (!dlist_empty(&g_data.idle_list)) {
        Conn* conn = container_of(g_data.idle_list.next, &Conn::idle_node);
        if (conn == nullptr){
          break;
        }
        uint64_t next_ms = conn->last_active_ms + k_idle_timeout_ms;
        if (next_ms >= now_ms) {
            break; // not expired
        }
        fprintf(stderr, "removing idle connection: %d\n", conn->fd);
        conn_destroy(conn);
    }
}
static auto next_timer_ms() -> int32_t {
    if (dlist_empty(&g_data.idle_list)) {
        return -1; // no timers, no timeouts
    }
    uint64_t now_ms = get_monotonic_msec();
    Conn* conn = container_of(g_data.idle_list.next, &Conn::idle_node);
    if (conn == nullptr) {
        return 0;
    }
    uint64_t next_ms = conn->last_active_ms + k_idle_timeout_ms;
    if (next_ms <= now_ms) {
        return 0; // missed?
    }
    return (int32_t)(next_ms - now_ms);
}
